### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by smongey** [mec/kirby-simple-api#1]
This doesn’t seem to output any files that might be part of a pages content.
Is there a particular reason this isn’t accounted for? Or is this aim to really just keep this “super simple” :)

**Comment by mec** [comment]
No reason other than it's only an example to go along with the article:

https://medium.com/@mecrawlings/decoupled-kirby-d22416f567e9

Have a look at the advanced branch, which outputs the URLs to images for content and use that as a base for files:

https://github.com/mec/kirby-simple-api/tree/advanced

The advanced branch was the one I used to re-create the starterkit with React which is over here:

https://github.com/mec/react-kirby-frontend
