### ISSUE TITLE
Parse structure field YAML data

### ISSUE THREAD

**Issue by rafegoldberg** [mec/kirby-simple-api#3]
Been playing with this a bit further and noticed that the plugin doesn't parse structure fields from their YAML format. Instead it just returns a raw string representation, like so:

<img width="685" alt="untitled" src="https://user-images.githubusercontent.com/886627/34586281-32071290-f158-11e7-9dd4-2ba10ae495f7.png">

Would be a nice convenience to auto-parse structure fields.

**Comment by rafegoldberg** [comment]
Ah, I didn't realize that Kirby structure fields are _expected_ to return an unparsed YAML string. Closing this, as it seems out of the scope of a simple API plugin!

**Comment by mec** [comment]
Yeah for sure. Also the API is only really here to go with the article I wrote: https://medium.com/@mecrawlings/decoupled-kirby-d22416f567e9. I think there are some full on api plugins about, but when it's this simple do we really need them? :) Also check out the React front end I built to go with this (if you like that kind of thing!) https://github.com/mec/react-kirby-frontend
